Update control

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -5,6 +5,8 @@
 pid=/opt/repo/pid/redis.pid
 sentinel_pid=/opt/repo/pid/redis-sentinel.pid
 
+SENTINEL_ON="1"
+
 if [ -n $REDIS_PASSWORD ]; then
     CLI_AUTH="-a $REDIS_PASSWORD"
 fi
@@ -13,25 +15,35 @@ fi
 REDIS_CLI="-h $OPENSHIFT_REDIS_HOST -p $OPENSHIFT_REDIS_PORT $CLI_AUTH"
 REDIS_SENTINEL_CLI="-h $OPENSHIFT_REDIS_SENTINEL_HOST -p $OPENSHIFT_REDIS_SENTINEL_PORT $CLI_AUTH"
 
-function status() {
-    client_result $pwd
-    if [ -f $pid ] && ( kill -0 $(cat $pid) ); then
-        client_result "Redis is running"
-        if [ "$REDIS_DB_MASTER" == "1" ]; then
-            client_result "  master (receives writes), mode ${REDIS_DB_MODE:-sharded}"
-        else
-            client_result "  slave"
-        fi
-        client_result "  Connect to: $OPENSHIFT_GEAR_DNS:$OPENSHIFT_REDIS_PROXY_PORT password: $REDIS_PASSWORD"
-    else
-        client_result "Redis is not running"
-    fi
+function start() {
+    [ -f $pid ] && [ -z $(ps aux|grep "redis-server" | grep -v "redis-sentinel" | grep -v grep) ] && rm -f $pid;
+    [ -f $sentinel_pid ] && [ -z $(ps aux|grep "redis-sentinel" | grep -v grep) ] && rm -f $sentinel_pid;
+    if ! [ -f $pid ]; then
+        kill -9 $(ps aux|grep "redis-server" | grep -v "redis-sentinel" | grep -v grep | awk '{print $2}') 2>/dev/null;
+        chmod 755 /opt/repo/env;
+        echo $REDIS_CLI > /opt/repo/env/REDIS_CLI;
+        erb /opt/repo/conf/redis.conf.erb > /opt/repo/conf/redis.conf; /opt/repo/versions/${Version}/bin/redis-server /opt/repo/conf/redis.conf
 
-    if [ -f $sentinel_pid ] && ( kill -0 $(cat $sentinel_pid) ); then
-        client_result "Redis Sentinel is running"
-        client_result "  Connect to: $OPENSHIFT_GEAR_DNS:$OPENSHIFT_REDIS_SENTINEL_PROXY_PORT password: $REDIS_PASSWORD"
+        ret=$?
+        if [ $ret -ne 0 ]; then
+            echo "Redis failed to start - $ret" 1>&2
+            return $ret
+        fi
+        echo "Redis node started successfully!"
     else
-        client_result "Redis Sentinel is not running"
+        echo "Redis server is already started"
+    fi
+    if [ $SENTINEL_ON == "1" ]; then
+    	if ! [ -f $sentinel_pid ]; then
+            kill -9 $(ps aux| grep "redis-sentinel" | grep -v grep | awk '{print $2}') 2>/dev/null;
+            echo $REDIS_SENTINEL_CLI > /opt/repo/env/REDIS_SENTINEL_CLI
+            erb /opt/repo/conf/redis-sentinel.conf.erb > /opt/repo/conf/redis-sentinel.conf; /opt/repo/versions/${Version}/bin/redis-sentinel /opt/repo/conf/redis-sentinel.conf
+            ret=$?
+            if [ $ret -ne 0 ]; then
+                echo "Redis Sentinel failed to start - $ret" 1>&2
+                return $ret
+            fi
+    	fi
     fi
 }
 
